### ISSUE TITLE
第二章185行翻译有误

### ISSUE THREAD

**Issue by ghost** [Volong/logback-chinese-manual#2]
原文：However, if an ancestor of logger L, say P, has the additivity flag set to false, then L's output will be directed to all the appenders in L and its ancestors up to and including P but not the appenders in any of the ancestors of P.

译文：如果 *L* 的子级 logger 为 *P*，且 *P* 设置了 additivity = false，那么 *L* 的日志会在 *L* 所有 的 appender 包括 *P* 本身的 appender 中输出，但是不会在 *P* 的子级 appender 中输出。

ancestor 的意思希望能更正。

**Comment by YLongo** [comment]
不好意思才看到。
已更正，感谢🙏
