### ISSUE TITLE
关于第二章中Appender Additivity的翻译问题

### ISSUE THREAD

**Issue by AngerWind** [Volong/logback-chinese-manual#5]
根据http://logback.qos.ch/manual/architecture.html对于Appender Additivity的描述：The output of a log statement of logger L will go to all the appenders in L and its ancestors. 
![image](https://user-images.githubusercontent.com/42960576/115376371-399a1b80-a201-11eb-9b8a-02b3d92c4b22.png)
此处大致的翻译是：logger L的输出日志会被输出到他自身与父层级的appenders中。
而不是“logger L 的日志输出语句会遍历 L 和它的子级中所有的 appender”。
子级修改为父层级

**Comment by YLongo** [comment]
这个错误之前有人提出过，我修改了，但是没有同步到GitBook。我同步一下。

谢谢。
